#!/bin/sh
git checkout gh-pages                                           #switch to gh-pages branch
git checkout master -- README.md                                #checkout just README.md from master
git mv README.md _includes
git commit -m "Sync README.md from master"                      #commit the changes
# git push                                                      #uncomment if you want to auto-push
git checkout master                                             #switch back to the master branch
